version: "3.7"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    command: /bin/bash -c "gunicorn app:app -b 0.0.0.0:5000 --reload"
    links:
      - database
    volumes:
      - ./backend:/app
    expose:
      - 5000
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - 443:443
    depends_on:
      - backend

volumes:
  postgres_data:
